apiVersion: apps/v1
kind: Deployment
metadata:
  name: captcha-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: captcha
  template:
    metadata:
      labels:
        app: captcha
    spec:
      containers:
        - name: captcha
          image: wsqun/svc-captcha:1.0.1
          resources: # 资源配额
            limits:  # 限制资源（上限）
              cpu: "2" # CPU限制，单位是core数
              memory: "100Mi" # 内存限制
            requests: # 请求资源（下限）
              cpu: "1"  # CPU限制，单位是core数
              memory: "10Mi"  # 内存限制
        ports:
          - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: captcha-service-clusterip
  namespace: dev
spec:
  selector:
    app: captcha
  type: ClusterIP
  ports:
    - port: 8085  # Service端口
      targetPort: 8085 # pod端口